export const conversation = [
  {
    id: 1,
    from: 'Martin',
    to: '_SERVER',
    body: 'Hola! Necesito informacion sobre ventas',
    type: 'TEXT',
    date: '01/03/2023 14:44:22',
    read: false,
    send: true,
  },
  {
    id: 2,
    from: '_SERVER',
    to: 'Martin',
    body: 'Whatsapp ',
    type: 'TEXT',
    date: '01/03/2023 14:44:24',
    read: false,
    send: true,
  },
  {
    id: 3,
    from: '_SERVER',
    to: 'Martin',
    body: 'Telefono',
    type: 'BUTTON',
    date: '01/03/2023 14:44:24',
    read: false,
    send: true,
  },
  {
    id: 4,
    from: '_SERVER',
    to: 'Martin',
    body: 'Correo Electronico',
    type: 'BUTTON',
    date: '01/03/2023 14:44:24',
    read: false,
    send: true,
  },
];
